hamlet-io/executor-python

- .cmdb/test_product_id/config/solutionsv2/alm/environment.json
- .gitignore
Some minor tweaks from testing
> <fix> CMDB fixup and ignore dymaic templates

- gen3-cli/Makefile
- gen3-cli/cot/command/create/blueprint.py
- gen3-cli/cot/command/create/template.py
- gen3-cli/cot/command/manage/__init__.py
- gen3-cli/cot/utils/__init__.py
1. Fixed makefile lint command
2. Fixed linter error mention by @koriaf in #4
> Fixed pep errors + fixed makefile lint command.

- gen3-cli/cot/command/create/__init__.py
- gen3-cli/cot/command/create/blueprint.py
- gen3-cli/cot/command/create/build_blueprint.py
- gen3-cli/cot/command/create/reference.py
- gen3-cli/cot/command/create/template.py
- gen3-cli/cot/command/manage/__init__.py
- gen3-cli/cot/command/manage/credentials_crypto.py
- gen3-cli/cot/command/manage/crypto.py
- gen3-cli/cot/command/manage/file_crypto.py
Wrappers:
1. manageCredentialCrypto.sh
1. manageFileCrypto.sh
1. createBuildBlueprint.sh
1. createReference.sh
1. manageCrypto.sh
I didn't manage to run them properly, but I'm going to do this in the testing phase.
> Sh script wrappers

- gen3-cli/cot/backend/generate/cmdb/account/__init__.py
- gen3-cli/cot/backend/generate/cmdb/tenant/__init__.py
- gen3-cli/cot/backend/generate/product/app_lifecycle_mgmt/__init__.py
- gen3-cli/cot/backend/generate/product/base/__init__.py
- gen3-cli/cot/backend/generate/product/django/__init__.py
- gen3-cli/cot/backend/generate/utils.py
- gen3-cli/cot/command/create/blueprint.py
- gen3-cli/cot/command/create/template.py
- gen3-cli/tests/unit/command/create/test_blueprint.py
- gen3-cli/tests/unit/command/create/test_template.py
1. create blueprint deployment_unit option removed
2. create template blueprint level option removed
3. generalization of the generation backend
> Fixes + Improvements:

- gen3-cli/cot/command/generate/cmdb.py
- gen3-cli/cot/command/generate/product.py
- gen3-cli/cot/utils/__init__.py
- gen3-cli/tests/unit/command/generate/cmdb/test_account.py
- gen3-cli/tests/unit/command/generate/cmdb/test_tenant.py
- gen3-cli/tests/unit/command/generate/product/test_app_lifecycle_mgmt.py
- gen3-cli/tests/unit/command/generate/product/test_base.py
- gen3-cli/tests/unit/command/generate/product/test_django.py
- gen3-cli/tests/unit/command/generate/test_generate_command.py
- gen3-cli/tests/unit/command/generate/utils.py
Added semi-automated tests for generate commands cli.  Nothing special, pretty similar to what I did previously with shell scripts wrappers cli testing.
> Generate cli test

- gen3-cli/cot/backend/common/runner.py
- gen3-cli/cot/backend/create/reference/__init__.py
- gen3-cli/cot/backend/create/template/__init__.py
- gen3-cli/cot/backend/manage/credential_crypto/__init__.py
- gen3-cli/cot/backend/manage/crypto/__init__.py
- gen3-cli/cot/backend/manage/deployment/__init__.py
- gen3-cli/cot/backend/manage/file_crypto/__init__.py
- gen3-cli/cot/backend/manage/stack/__init__.py
- gen3-cli/cot/backend/run/expo_app_publish/__init__.py
- gen3-cli/cot/backend/run/lambda_func/__init__.py
- gen3-cli/cot/backend/run/pipeline/__init__.py
- gen3-cli/cot/backend/run/sentry_release/__init__.py
- gen3-cli/cot/backend/run/task/__init__.py
- gen3-cli/cot/command/create/blueprint.py
- gen3-cli/cot/command/create/reference.py
- gen3-cli/cot/command/manage/credentials_crypto.py
- gen3-cli/cot/command/manage/crypto.py
- gen3-cli/cot/command/manage/deployment.py
- gen3-cli/cot/command/manage/file_crypto.py
- gen3-cli/cot/command/manage/stack.py
- gen3-cli/cot/command/run/expo_app_publish.py
- gen3-cli/cot/command/run/lambda_func.py
- gen3-cli/cot/command/run/pipeline.py
- gen3-cli/cot/command/run/sentry_release.py
- gen3-cli/cot/command/run/task.py
- gen3-cli/cot/utils/__init__.py
1. Fixed keyboard interrupt issue https://taiga-gosource.codepublican.io/project/roleyfoley-codeontap-cli/issue/73
1. Generalized sh script runner
> FIX:keyboard interrupt issue

- gen3-cli/cot/backend/test/templates/cfn_structure_obj_block.py
- gen3-cli/tests/data/integration/backend/test/cf/valid-syntax.json
- gen3-cli/tests/integration/backend/test/test_utils.py
Minor fix to cfn_structure testing to correct Output Key
> <fix> cfn_outputs test structure

- gen3-cli/.flake8
- gen3-cli/cot/backend/common/context.py
- gen3-cli/cot/backend/common/fsutils.py
- gen3-cli/cot/backend/common/shell_vars_to_json.py
- gen3-cli/cot/backend/common/shell_vars_to_json.sh
- gen3-cli/cot/backend/create/template/context_tree.py
- gen3-cli/cot/backend/create/template/create_template.py
- gen3-cli/cot/backend/create/template/environment.py
- gen3-cli/cot/backend/create/template/set_context.py
- gen3-cli/cot/backend/create/template/utils.py
- gen3-cli/tests/conftest.py
- gen3-cli/tests/integration/backend/create/template/conftest.py
- gen3-cli/tests/integration/backend/create/template/test_context_tree.py
- gen3-cli/tests/integration/backend/create/template/test_set_context.py
- gen3-cli/tests/integration/backend/create/template/test_utils.py
- gen3-cli/tests/unit/backend/common/test_context.py
So, this is almost one to one rewriting of the setContext.sh. This approach has its own problems. The main one is that it's not a final solution, just a temporary measure to make codebase testable and upgradable.  My next move is implementation of the CMDB upgrade functionality and after that, I'll jump to the reimplementation of the createTemplate.sh.  Technically this will not be difficult, because the main problem that bothered me during my previous attempts to rewrite createTemplate.sh is solved. The problem was env variables, specifically their scope. In the future, I plan to further develop Environment class into a better-structured context class and keep the overall workflow pretty similar to what we have now in our shell script, fixing only things that should be fixed. 
PROGRESS: …
> WIP: create template shell script replacement

- gen3-cli/cot/backend/common/context.py
- gen3-cli/cot/backend/test/renderer/testcases_template.py
- gen3-cli/tests/data/integration/backend/test/cf/structure.json
- gen3-cli/tests/data/integration/backend/test/testcase/json-structure-bad-testcase.json
- gen3-cli/tests/data/integration/backend/test/testcase/json-structure-good-testcase.json
- gen3-cli/tests/integration/backend/test/test_run.py
1. Fixed incorrect context errors handling
1. Fixed incorrect value types in testcases
> Bug Fixes:

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Standardise the format of issues/PRs.
> <feature> github templates

- hamlet-cli/hamlet/command/create/reference.py
Fix reference to cot python module instead of hamlet
cli was failing 
Tested locally
> Fix cot reference

- hamlet-cli/hamlet/command/create/template.py
- hamlet-cli/tests/unit/command/create/test_template.py
Add deployment level of `schema` to the CLI to enable Schema Generation.
Currently only available by calling the `createTemplate.sh` script directly.
CLI development container environment - was successful for both schema types.
> feat(schema): add template level of schema for schema generation

- hamlet-cli/hamlet/command/common/display.py
Fixes #53 
A previous attempt didn't quite do the job
Allows for displaying integers as part of a table output 
Tested locally
> fix: handle ints in table outputs

- hamlet-cli/hamlet/__init__.py
- hamlet-cli/hamlet/command/common/context.py
- hamlet-cli/hamlet/command/common/exceptions.py
- hamlet-cli/hamlet/command/deploy/__init__.py
- hamlet-cli/hamlet/command/entrance/__init__.py
- hamlet-cli/hamlet/command/generate/cmdb.py
- hamlet-cli/hamlet/command/manage/credentials_crypto.py
- hamlet-cli/hamlet/command/manage/crypto.py
- hamlet-cli/hamlet/command/manage/deployment.py
- hamlet-cli/hamlet/command/manage/file_crypto.py
- hamlet-cli/hamlet/command/manage/stack.py
- hamlet-cli/hamlet/command/run/expo_app_publish.py
- hamlet-cli/hamlet/command/run/lambda_func.py
- hamlet-cli/hamlet/command/run/pipeline.py
- hamlet-cli/hamlet/command/run/sentry_release.py
- hamlet-cli/hamlet/command/run/task.py
- hamlet-cli/hamlet/command/schema/__init__.py
- hamlet-cli/tests/unit/command/deploy/test_deploy.py
- hamlet-cli/tests/unit/command/generate/cmdb/test_account.py
- hamlet-cli/tests/unit/command/schema/test_create.py
- hamlet-cli/tests/unit/command/schema/test_list.py
- hamlet-cli/tests/unit/command/test_option_generation.py
Introduce new `hamlet schema` top-level CLI command
Note: requires https://github.com/hamlet-io/engine/pull/1518
[Recent engine updates ](https://github.com/hamlet-io/engine/pull/1516) have restructured JSONSchemas to be one definition per schema file. This means that there are now quite a number of schemas to generate and publish regularly. 
The introduction of the `schemaset` entrance in hamlet-io/engine#1516 allows for the creation of a `schemacontract`. This PR is to update the python executor to internet this contract type and both display or act upon the result using the existing `schema` entrance.
Locally.
> feat: hamlet schema command set

- hamlet-cli/hamlet/command/generate/product.py
Update minor descriptors that referenced a previous name for Hamlet.
Consistency
n/a
n/a
> chore: remove outdated ref to codeontap

- README.md
Outlines the different processes available to install the hamlet-cli for development purposes
A common method of testing and developing the cli is to use an existing hamlet CMDB and workspace. This allows for broader testing of the cli and also tests usability in real world scenarios. 
Including the installation process for an exsting workspace makes this easier to manage
Tested locally
> feat: add different development processes

- hamlet-cli/hamlet/backend/common/runner.py
Fixes #93 
- Uses  subprocess.communicate() instead of subprocess.wait() which is the recommended approach when dealing with outputs
- Adds  shutil.which() to locate bash for compatibility with different installations and confirm that generation dir is available before running the command
Some errors that are raised from hamlet include full blueprints or large exceptions. The subprocess.wait() function can deadlock on large outputs when the allocated buffer is larger than the message.
See: https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait 
Tested locally and using test suite
> fix: handle large outputs in runner calls

- hamlet-cli/hamlet/backend/common/context.py
- hamlet-cli/hamlet/backend/common/exceptions.py
- hamlet-cli/hamlet/backend/draw/diagram.py
- hamlet-cli/hamlet/backend/query/__init__.py
- hamlet-cli/hamlet/backend/test/generate.py
- hamlet-cli/hamlet/command/common/decorators.py
- hamlet-cli/hamlet/command/common/exceptions.py
- hamlet-cli/hamlet/command/deploy/__init__.py
- hamlet-cli/hamlet/command/entrance/__init__.py
- hamlet-cli/hamlet/command/manage/credentials_crypto.py
- hamlet-cli/hamlet/command/manage/crypto.py
- hamlet-cli/hamlet/command/manage/deployment.py
- hamlet-cli/hamlet/command/manage/file_crypto.py
- hamlet-cli/hamlet/command/manage/stack.py
- hamlet-cli/hamlet/command/query/__init__.py
- hamlet-cli/hamlet/command/run/expo_app_publish.py
- hamlet-cli/hamlet/command/run/lambda_func.py
- hamlet-cli/hamlet/command/run/pipeline.py
- hamlet-cli/hamlet/command/run/sentry_release.py
- hamlet-cli/hamlet/command/run/task.py
- hamlet-cli/hamlet/command/schema/__init__.py
- hamlet-cli/hamlet/command/setup/__init__.py
- hamlet-cli/hamlet/command/test/generate.py
- hamlet-cli/hamlet/command/visual/__init__.py
- hamlet-cli/tests/integration/backend/test/test_generate.py
moves backend exception handling into a decorator instead of adding to
each command individually
This creates a consistent error handling approach for backend exceptions
which usually require user intervention and are outside of what the
hamlet-cli can handle
Tested locally and using test suite
> refactor: backend exception handling in cli

- README.md
Updates the basic install docs to align with pip style installation process and remove the requirement for make
Makes it easier to install and use the hamlet cli for base users. The development process does require some extra dependencies like any development workflow does 
Tested locally
> refactor: update basic install docs

- hamlet-cli/README.md
Use an actual file instead of a symlink as this breaks packaging
Fix issue with installing from local location
Tested locally
> fix: add readme for package

- .github/workflows/release.yml
- hamlet-cli/.bumpversion.cfg
- hamlet-cli/requirements/dev.txt
- hamlet-cli/setup.py
Publishes the latest version of the cli to pypi on build 
Keeps the hamlet-cli up to date and availble through pypi
Tested locally
> fix: packaging support for pypi

- .github/workflows/testing.yml
- README.md
- hamlet-cli/README.md
- Documentation (new or update to existing)
Updates the repo and package README files to provide more information on the install process and to redirect audiences between the different pages
Make it easier to find out what hamlet does on pypi and how to get started with 
Move users to the user docs instead of using the development install process 
closes #134 
Tested locally
- None
- None
- None
> feat: update docs to outline install process

- hamlet-cli/hamlet/command/__init__.py
- hamlet-cli/hamlet/command/common/setup.py
- hamlet-cli/hamlet/command/engine/__init__.py
- hamlet-cli/hamlet/utils/__init__.py
Adds handling of permissions issues on the HAMLET_HOME_DIR some comands will still work so we continue with the command but will raise a warning whenever the command is called
fixes #146 
- None
- None
- None
> fix: handle permissions on home dir

- hamlet-cli/hamlet/__about__.py
Fix the package name that is used for setup.py
Publishing of the package was broken 
- None
- None
- None
> fix: set title to package name

- .github/workflows/changelog.yml
- .github/workflows/release.yml
- Changes the release trigger to run off successful completion of testing
- Sets a specific branch for the version bump PR to avoid overwriting the change log
- Makes the changelog PR a draft so that it can be kept quiet and merged on release
Reduces what needs to be done in each workflow 
Makes sure we can keep our pipelines independent 
- None
- None
- None
> refactor(ci): release trigger process

- hamlet/backend/engine/engine.py
- hamlet/backend/engine/engine_code_source.py
- hamlet/backend/engine/engine_loader.py
- hamlet/backend/engine/engine_source.py
- hamlet/command/__init__.py
- hamlet/command/common/config.py
- hamlet/command/common/decorators.py
- hamlet/command/common/engine_setup.py
- hamlet/command/engine/__init__.py
- tests/unit/backend/engine/test_engine.py
- Adds a cache timeout for automatic update checking to reduce external calls on each run of hamlet commands
- Adds an engine state version to allow for changes to the state file. If an older version of the state is found the engine raise an error that it needs to be reinstalled 
- removes the auto install process and replaces with an update check process which prompts you to update your engine
- Adds build state reporting to show more details on how the engine was made
- Adds handling for issues that occur during auto updates and for calls to external sources
This makes handling engine updates safer and reduces the potential risks of issues occurring with the automatic engine checking which …
> refactor: engine update handling

- hamlet/backend/engine/__init__.py
- hamlet/backend/engine/engine_loader.py
- hamlet/command/common/engine_setup.py
- hamlet/command/engine/__init__.py
- tests/unit/backend/engine/test_engine.py
- tests/unit/command/engine/test_engine.py
adds an option on engine loading to control when external loading vs local loading can occur
Reduces network I/O when its not required and reduces the calls required for commands that use the engine rather than manage it 
tested locally and with local provider
- None
- None
- None
> refacctor: add local checking for engine loading

- .github/workflows/changelog.yml
Update the unreleased section to latest 
Make the changelog align with tags
Tested locally
- None
- None
- None
> fix: changelog details

- hamlet/command/deploy/run.py
Fixes a bug where the options provided to the root cli where not passed to the deployment commands
Deployment commands were failing to run
Tested locally
- None
- None
- None
> fix(deploy): include options when running deploys

- hamlet/backend/engine/__init__.py
- hamlet/backend/engine/engine.py
- hamlet/backend/engine/engine_loader.py
- hamlet/backend/engine/exceptions.py
- hamlet/command/common/engine_setup.py
- hamlet/command/engine/__init__.py
- hamlet/command/query/__init__.py
- adds docs to some classes and methods for automated generation
- uses click deprecated flag to mark query command group as deprecated
- moves exceptions into their own module
Easier documentation and standardise formatting
tested locally
- None
- None
- None
> refactor: general docs updates and tidy up

- hamlet/__about__.py
- setup.py
- Documentation (new or update to existing)
Fix the repository url about details to point to the github repo
Repo url was invalid and created a 404
- None
- None
- None
> fix(ci): update repository url

- hamlet/command/engine/__init__.py
minor fix for engine commands that were using the wrong function
Updated and install scripts were failing
Tested locally
- None
- None
- None
> fix: wrong function call for digest

- CONTRIBUTING.md
- hamlet/command/common/engine_setup.py
- hamlet/command/engine/__init__.py
- Documentation (new or update to existing)
- Add content flagging the need to use the update flag to trigger updates if the engine is already installed.
- Update the instructions provided if checking for updates on startup to include the update flag.
- Update the instructions on locally installing hamlet
- Make cli easier to use
- Make dev configuration accurate
Local execution.
- None
- None
- None
> chore: update engine install documentation

- hamlet/command/common/exceptions.py
- hamlet/command/component/describe_occurrence.py
- Adds command exception handling for http based exceptions which are often based on issues with the client
- Adds handling for describe-occurence when the occurrence can not be found
Fixes #224 
Provides more user friendly handling of exceptions raised by backend services 
Tested locally
- None
- None
- None
> fix: handle user facing errors

- hamlet/backend/container_registry/__init__.py
- setup.py
- align our httpx usage with the latest version of the package and locks the version down to a tighter version to prevent issues
Engine installation was failing due to api changes in httpx
- None
- None
- None
> fix: httpx package dep changes

- hamlet/backend/automation/save_cmdb_repos/__init__.py
- hamlet/backend/automation_tasks/save_repos/__init__.py
- hamlet/backend/common/runner.py
- hamlet/command/cmdb/__init__.py
- Splits out the commit message to align with conventional commit format that we use when saving CMDB chnges 
- Fixes an issue where booleans weren't being converted to a string representation 
- allows for commit changes to be deferred but save common messages as required
Makes it easier for CMDB saving to be handled in any pipeline 
- None
- None
- None
> feat: commit changes message extensions

- hamlet/backend/automation_tasks/transfer_image/__init__.py
get source automation properties after constructing the CMDB tree to ensure that folder structures are avialable
Fixes issues where the account details could not be found when using the automation style of finding directories. Also cleans up the setup process
Tested locallly
- None
- None
- None
> fix: run automation properties after construct

- hamlet/backend/container_registry/__init__.py
- setup.py
- fixes install_requires for package limits
- reverts changes added for httpx that are introduced in a beta release
Installation issues when a preinstall package is available and doesn't align with required package
- None
- None
- None
> fix: package dependency updates

- hamlet/backend/test/renderer/testcases_template.py
- hamlet/backend/test/templates/cfn_testcase_block.py.tmpl
Use an in check for test tools as they are no longer booleans and instead have their own dictionary of config
Testing tools like cfn_lint and checkov not included in testing 
- None
- None
- None
> fix(test): use dict check for testing tools

- README.md
- fixes the getting started install link
- fixes casing on hamlet and removes reference to deploy
- adds purpose for this repository
Clearer understanding of what the repo is for and fixes install link that is on pypi site
- None
- None
- None
> fix(docs): updates to README

- hamlet/command/generate/cmdb.py
- hamlet/command/generate/decorators.py
- hamlet/utils/__init__.py
- setup.py
- tests/unit/command/generate/test_generate_command.py
- Updates click to the latest major version 8.x
- Replaces the prompt handling for generate cmdb to align with changes to version 8.x for handling prompts
- Updates dynamic default handling to align with 8.x changes
This keeps hamlet up to date with what has been released by our core cli service 
tested locally
- None
- None
- None
> feat: update to click 8.x

- hamlet/command/layer/__init__.py
- tests/unit/command/layer/test_describe.py
- tests/unit/command/layer/test_list.py
- tests/unit/command/layer/test_query.py
- Moves to using name instead of id for describe
- Include name, id and active state in list
- Fix testing to remove copy mistakes
The move to name aligns with other commands and with what people see when looking through a CMDB
Tested locally
- None
- None
- None
> feat: layer info updates

- hamlet/backend/create/template/__init__.py
- hamlet/command/schema/__init__.py
- tests/unit/command/schema/test_create.py
- tests/unit/command/schema/test_list.py
- Replaces the type and instance schema options with a single schema option
Aligns with https://github.com/hamlet-io/engine/pull/1887
- None
- https://github.com/hamlet-io/engine/pull/1887
- None
> refactor: schema generation commands

- hamlet/command/release/__init__.py
- Allows for providing the new image format via cli
Allows for validation at the point of calling the cli and understanding of the available formats
- None
- None
- None
> feat: add support for new lambda_jar image format

- hamlet/backend/common/aws_credentials_session.py
- hamlet/backend/common/runner.py
- hamlet/backend/contract/__init__.py
- hamlet/backend/contract/tasks/aws_decrypt_kms_ciphertext/__init__.py
- hamlet/backend/contract/tasks/conditional_stage_skip/__init__.py
- hamlet/backend/contract/tasks/exceptions.py
- hamlet/backend/contract/tasks/rename_file/__init__.py
- hamlet/backend/contract/tasks/set_provider_credentials/__init__.py
- hamlet/backend/contract/tasks/start_ssh_shell/__init__.py
- Adds support for executing contracts as part of the hamlet cli
- Adds tasks to support the execution of runbook contracts
- Adds an aws credentials handler which uses the aws cli cache to retrieve temporary credentials instead of the boto cache. This allows for sharing credentials between hamlet bash calls and hamlet cli aws call
- Adds support in the runner for including additional tasks on the end of a script. Useful for piping results or extracting environment
The primary motivation for this change is to demonstrate the idea of executing contracts issued by the engine. The first prototype of this approach is through runbooks which are implemented as contracts from hamlet and included steps and stages to complete small tasks …
> feat: contract execution

- setup.py
- add fabric as dependency
Package required for ssh support in contract execution
Tested locally
- None
- None
- None
> fix: add fabric as dependency

- hamlet/backend/contract/__init__.py
- hamlet/backend/contract/tasks/ssh_copy_file/__init__.py
- hamlet/backend/contract/tasks/ssh_run_command/__init__.py
- Adds support for an ssh based file copy from a remote source to a local path
- Renames the start_ssh_shell to align with the rename of the task in the engine
- Adds support for substitution of input and output values during contract processing
ssh copy allows for pulling and pushing files from a local store into an environment 
substitution allows for incorporating values  into more complex commands as required
- None
- None
- None
> feat(task): add ssh copy file implementation

- hamlet/backend/common/aws_ssm_session.py
- hamlet/backend/contract/__init__.py
- hamlet/backend/contract/tasks/aws_ec2_select_instance/__init__.py
- hamlet/backend/contract/tasks/aws_ecs_run_command/__init__.py
- hamlet/backend/contract/tasks/aws_ecs_select_task/__init__.py
- hamlet/backend/contract/tasks/bash_run_command/__init__.py
- hamlet/backend/contract/tasks/ssh_copy_file/__init__.py
- hamlet/backend/contract/tasks/ssh_run_command/__init__.py
- setup.py
- Adds support for including a gateway ssh host when running commands or copying files. This enables support for using the bastion to access other hosts
- Adds a selection for the available instances based on a filter. Includes a preview page with additional info to make the selection
- Adds a selection for the running tasks for a give service or task family. Includes a preview page with additional info to make the selection
- Adds a standard wrapper for running ssm sessions using the AWS SSM plugin for aws cli as a backend to handle websocket connection
- Adds support for using ecs_run_command which uses ssm sessions to run interactive commands on ECS hosted containers
- Adds …
> feat: additional contract tasks

- hamlet/backend/container_registry/__init__.py
- hamlet/backend/engine/__init__.py
- hamlet/backend/engine/engine.py
- hamlet/backend/engine/loaders/base.py
- hamlet/backend/engine/loaders/tram.py
- hamlet/command/__init__.py
- hamlet/command/common/engine_setup.py
- hamlet/command/common/exceptions.py
- hamlet/command/engine/__init__.py
- tests/system/cmdb/product/step_1_install_engine.py
- tests/unit/backend/engine/test_engine.py
- tests/unit/command/engine/test_engine.py
- Adds engine locations to control when different engines are loaded
- Removes the overlay of remote engines over installed engines
- Reduces update caching and content caching to simplify process
- Only load installed engines by default to reduce risk of failure for standard deployment commands
- Fixes #285 
The engine management process was getting quite complex and had a few different ideas merged into it. This reduces it down to an less complex approach which aligns with the idea that engine management is a more advanced feature and allows users to get going quickly without noticing the more advanced options at first.
With this change Update available has been removed and replaced with a …
> refactor: engine management

- hamlet/backend/run/sentry_release/__init__.py
- hamlet/command/run/sentry_release.py
- tests/unit/command/run/test_sentry_release.py
- Align the sentry release command with the latest options for the backend
Allows for the use of the latest sentry release backend via the cli
Tested locally
- None
- None
- None
> feat: update sentry_release command

- setup.py
- older jinja was tracking a dependency that introduced a breaking change
New installs of the hamlet cli were failing
Tested locally
- None
- None
- None
> fix: update jinja to latest release

- hamlet/backend/common/runner.py
- hamlet/backend/contract/__init__.py
- hamlet/backend/contract/tasks/set_provider_credentials/__init__.py
- hamlet/backend/setup/__init__.py
- hamlet/command/cmdb/__init__.py
- hamlet/command/entrance/__init__.py
- hamlet/command/layer/__init__.py
- hamlet/command/manage/credentials_crypto.py
- hamlet/command/manage/crypto.py
- hamlet/command/manage/deployment.py
- hamlet/command/manage/file_crypto.py
- hamlet/command/manage/stack.py
- hamlet/command/reference/__init__.py
- hamlet/command/release/__init__.py
- hamlet/command/run/expo_app_publish.py
- hamlet/command/run/lambda_func.py
- hamlet/command/run/pipeline.py
- hamlet/command/run/sentry_release.py
- hamlet/command/run/task.py
- hamlet/command/schema/__init__.py
- hamlet/command/setup/__init__.py
- hamlet/command/task/__init__.py
- hamlet/command/visual/__init__.py
- cover the rest of the backend commands used in the cli to pass the engine through to the backend.
- A number of them were missed in the initial implementation
Commands were failing as the engine was not being passed correctly to backend functions
Tested locally
- None
- None
- None
> fix: pass engine context to all backend commands

- hamlet/command/common/config.py
- hamlet/command/common/decorators.py
- uses dynamic search path for loading cli profiles
Profiles were failing to load with updates to loading cli profiles from a given directory
tested locally
- None
- None
- None
> fix: loading of cli profiles

- hamlet/backend/query/__init__.py
- Handles empty outputs when the engine doesn't write a file as its empty
- Makes it easier to understand when a query doesn't return any file outputs
Tested locally
- None
- None
- None
> feat: add backend exception for missing query results

- hamlet/backend/engine/engine.py
- hamlet/backend/engine/loaders/unicycle.py
- hamlet/command/common/config.py
- hamlet/command/engine/__init__.py
- migrate to using the bundled engine-core for the unicycle
- move environment handling into the installed engine to allow for dynamically generating env values
- Use platform specific tags for container image sources
Migration to the new bundled engine which provides its own version of java
Tested locally
- https://github.com/hamlet-io/engine-core/pull/94
- https://github.com/hamlet-io/executor-bash/pull/315
- None
- None
> feat: bundled engine-core for unicycle

- hamlet/backend/contract/__init__.py
- hamlet/backend/deploy/__init__.py
- hamlet/backend/manage/credential_crypto/__init__.py
- hamlet/backend/manage/crypto/__init__.py
- hamlet/backend/manage/deployment/__init__.py
- hamlet/backend/manage/file_crypto/__init__.py
- hamlet/backend/manage/stack/__init__.py
- hamlet/command/deploy/test.py
- hamlet/command/task/__init__.py
- Missed some during previous updates
Commands failing as they were missing the engine env vars
Tested locally
- None
- None
- None
> fix: further engine passing updates for commands

- hamlet/backend/automation/confirm_builds/__init__.py
- hamlet/backend/automation/construct_tree/__init__.py
- hamlet/backend/automation/manage_build_references/__init__.py
- hamlet/backend/automation/manage_images/__init__.py
- hamlet/backend/automation/save_cmdb_repos/__init__.py
- hamlet/backend/automation/set_automation_context/__init__.py
- hamlet/backend/automation/update_build_references/__init__.py
- hamlet/backend/contract/tasks/set_provider_credentials/__init__.py
- hamlet/backend/create/template/__init__.py
- hamlet/backend/manage/credential_crypto/__init__.py
- hamlet/backend/manage/crypto/__init__.py
- hamlet/backend/manage/deployment/__init__.py
- hamlet/backend/manage/file_crypto/__init__.py
- hamlet/backend/manage/stack/__init__.py
- hamlet/backend/run/expo_app_publish/__init__.py
- hamlet/backend/run/lambda_func/__init__.py
- hamlet/backend/run/pipeline/__init__.py
- hamlet/backend/run/sentry_release/__init__.py
- hamlet/backend/run/task/__init__.py
- hamlet/backend/setup/__init__.py
- hamlet/backend/unitlist/__init__.py
Sets named parameters for all calls to the runner.run backend command
Run tasks failing and need to ensure they are easy to manage
Tested locally
- None
- None
- None
> fix: named params for runner invocation

- hamlet/backend/automation_tasks/save_repos/__init__.py
- hamlet/backend/automation_tasks/transfer_image/__init__.py
- hamlet/backend/automation_tasks/update_build/__init__.py
- hamlet/backend/automation_tasks/upload_image/__init__.py
- fixes up how the engine is passed to the automation tasks
Some more updates that were missed along the way
Tested locally
- None
- None
- None
> fix: passing engine to automation tasks

- hamlet/backend/manage/file_crypto/__init__.py
- hamlet/backend/run/task/__init__.py
- Typos not found during testing
Some more broken commands 
tested locally
- None
- None
- None
> fix: more engine parameters for runners

- hamlet/command/deploy/run.py
- Fixes parameter names for run_deployment
Not even sure where this came from??? 
Tested locally
- None
- None
- None
> fix: deploy parameter name

- .github/workflows/release.yml
- .github/workflows/style.yml
- Remove java configuration as its no longer required on unicycle
- Update python version to 3.9
- cleanup hamlet local install
Do less things 
Will be tested in pipeline
- None
- None
- None
> refactor(ci): update pipeline to align with latest cli

- hamlet/backend/contract/tasks/aws_lambda_invoke_function/__init__.py
- hamlet/backend/contract/tasks/aws_rds_create_snapshot/__init__.py
- Adds lambda invoke contract task
- Adds RDS create snapshot task
Continuing migration of run* commands from the bash executor over to the runbook/contract/python executor 
- None
- None
- None
> feat(contract): add aws tasks

- hamlet/backend/engine/loaders/tram.py
- hamlet/backend/engine/loaders/user.py
- for the latest tram use the bundled wrapper to ensure java11 is available
- for user engines resolve the absolute path provided for local_dir sources
Java 11 is now required for the engine-core so using the bundled wrapper ensures that this is aligned with the expected version 
Resolving the absolute path for the user engine fixes issues with plugins what require the full path
Tested locallly
- None
- None
- None
> fix: engine updates

- hamlet/backend/common/utilities.py
- Replaces strtobool with a local version of the function
distutils has been deprecated and will be removed in new versions of python
Tested locally
- None
- None
- None
> refactor: distutils strtobool

- hamlet/command/release/__init__.py
- tests/unit/command/release/test_list_image_references.py
- Adds a list command to show the image references and sources for all occurrences in a district
Shows information on what has been deployed into a district easily
tested locally
- https://github.com/hamlet-io/engine/pull/1967
- None
- None
> feat: add image reference listing

- hamlet/backend/contract/tasks/aws_ecs_run_task/__init__.py
Minor update to handle run task for ecs tasks that use the host networking instead of their own
task was failing to run as part of a runbook
Tested locally
- None
- None
- None
> fix: network configuration params for run task

- hamlet/command/common/config.py
- hamlet/command/common/decorators.py
- validate the root_dir configuration option to standardise how it is used
Fixes https://github.com/hamlet-io/engine/issues/1993 
Tested locallly
- None
- None
- None
> fix: resolve root dir to absolute path

- hamlet/backend/contract/tasks/aws_secretsmanager_get_secret_value/__init__.py
- Adds task to get a secrets manager secret and output the result
This allows for the use of secrets manager secrets in runbooks 
Tested locally
- None
- None
- None
> feat(task): add secrets manager task

- .github/workflows/changelog.yml
Use a shared action workflow for changelog generation
Makes it easier to manage changelog generation
Tested on AWS provider
- None
- None
- None
> refactor: changelog share pipeline

- hamlet/backend/contract/tasks/aws_ecr_docker_login/__init__.py
- hamlet/backend/contract/tasks/aws_s3_download_object/__init__.py
- hamlet/backend/contract/tasks/aws_s3_upload_object/__init__.py
- hamlet/backend/contract/tasks/cmdb_write_stack_output/__init__.py
- hamlet/backend/contract/tasks/conditional_stage_skip/__init__.py
- hamlet/backend/contract/tasks/docker_pull_image/__init__.py
- hamlet/backend/contract/tasks/docker_push_image/__init__.py
- hamlet/backend/contract/tasks/file_temp_directory/__init__.py
- hamlet/backend/contract/tasks/file_zip_path/__init__.py
- hamlet/backend/create/template/__init__.py
- hamlet/command/task/__init__.py
- setup.py
- Adds a collection of tasks to deal with images using tasks
These tasks allow for managing the images used with application components in hamlet. This includes S3 based zip files and docker images
Tested locally
- None
- None
- None
> feat: add support for image management via tasks

- .github/workflows/release.yml
- Updates to the action have changed the version structure
Release process wasn't working
- None
- None
- None
> fix(ci): update the gh action for pypi release

- setup.py
update setuptools_scm to latest version
pre-release versions not tagging properly
tested locally
- None
- None
- None
> fix: update setuuptools scm version

- .github/workflows/changelog.yml
- .github/workflows/release.yml
- .github/workflows/style.yml
Updates the shared github workflows used to the latest version
Resolves a bug in the changelog generation and moves to using the latest nodeJS version in the actions
- None
- None
- None
> chore: update github actions tasks to latest versions
