hamlet-io/executor-python

Makefile, gen3-cli/Makefile, gen3-cli/cot/command/create/template.py, gen3-cli/cot/command/manage/deployment.py, gen3-cli/cot/command/manage/stack.py
1. Changed ```deployment-unit``` and ```level``` options to mandatory in ```create template command```.
1. Restored original ```manage stack|deployment``` syntax. 
1. Renamed ```make ssh-gen3-client``` to ```make shell```
I'll move issues in taiga when this PR will be merged.
=> Several minor fixes for issues mentioned in taiga

README.md, gen3-cli/Makefile, gen3-cli/cot/command/create/__init__.py, gen3-cli/cot/command/create/blueprint.py, gen3-cli/cot/command/create/reference.py, gen3-cli/cot/command/manage/__init__.py, gen3-cli/cot/command/manage/credentials_crypto.py, gen3-cli/cot/command/manage/crypto.py, gen3-cli/cot/command/run/__init__.py, gen3-cli/cot/loggers.py, gen3-cli/tests/unit/command/create/test_blueprint.py, gen3-cli/tests/unit/command/create/test_build_blueprint.py, gen3-cli/tests/unit/command/create/test_reference.py, gen3-cli/tests/unit/command/create/test_template.py, gen3-cli/tests/unit/command/manage/test_credentials_crypto.py, gen3-cli/tests/unit/command/manage/test_crypto.py, gen3-cli/tests/unit/command/manage/test_deployment.py, gen3-cli/tests/unit/command/manage/test_file_crypto.py, gen3-cli/tests/unit/command/manage/test_stack.py, gen3-cli/tests/unit/command/run/test_expo_app_publish.py, gen3-cli/tests/unit/command/run/test_lambda_func.py, gen3-cli/tests/unit/command/run/test_pipeline.py, gen3-cli/tests/unit/command/run/test_sentry_release.py, gen3-cli/tests/unit/command/run/test_task.py, gen3-cli/tests/unit/command/test_option_generation.py
That's a huge pull request. A lot of code, a lot of the files changed. 
But in short, this is semi-automated testing for cli input validation.  The main file is **gen3-cli/tests/unit/command/test_option_generation.py.** It contains all test automation + tests for the automation itself.  You can see there that I don't use mock methods. That's is because they are unavailable. The reason as I suppose is an old version of python, 3.5 instead of 3.7. I already created an issue in taiga referencing this problem. But the workaround is pretty simple therefore not a big deal. 
As for the detailed explanation of what's going on with testing please read the file mentioned above. I left quite a few tests and docstrings there, so maybe that will be enough to understand everything.
=> Input validation unit tests

gen3-cli/cot/backend/manage/deployment/__init__.py, gen3-cli/cot/command/manage/deployment.py, gen3-cli/tests/unit/command/manage/test_deployment.py
Updating the options on ```cot manage deployment``` to reflect the changes made to the manageDeployment.sh script in codeontap/gen3#1090
- removed --deployment-name as its now being defined within the script and used to name the deployment but not the resultant resource group.
- added --resource-group -g to replace it.
=> removed deployment-name and replaced with resource-group option.

gen3-cli/MANIFEST.in, gen3-cli/setup.py
A couple of minor fixes from testing and installation into the codeontap/gen3 image 
- Template files not included in installed package for generating tests
- Add basic package requirements for setup
=> <fix> Include templates in setup

gen3-cli/setup.py
The setup requirements were newer than the requirements file versions specified. This allows for the older versions to be accepted
=> <fix> Align requirements and minimum setup

gen3-cli/cot/backend/create/template/__init__.py, gen3-cli/cot/command/create/template.py, gen3-cli/tests/unit/command/create/test_template.py
When the Input Sources on create template is set to "Mock", the output sources is a mandatory option.
```cot create template -i mock -o /opt/tempdir ...```
This PR implements the OUTPUT_DIR option so that it is available, however it does not enforce the mandatory nature of this argument as it is only mandatory under certain circumstances.
=> incorporated output option which is required for mocking.

gen3-cli/cot/backend/common/context.py, gen3-cli/cot/backend/query/__init__.py, gen3-cli/cot/command/query/__init__.py, gen3-cli/tests/unit/backend/query/test.py, gen3-cli/tests/unit/command/query/test.py
So, I did:
1. Split cot query command into 3 separated commands: 
1. cot query get
1. cot query list-tiers
1. cot query list-components
1. Completed list-components and list-tiers commands functionality.
1. Added testing for the cli and backend parts.
1. Added simple md5_hash method to Context class. It may be useful for caching because any string can be turned into a hash and a format of a hash will not change. 
1. Moved the table formatters from the backend to the cli part, just to split functionality and representation.
=> cot query command v2

gen3-cli/requirements/dev.txt, gen3-cli/requirements/prod.txt
minor change to requirements 
- pytest would be a production dependency now that its used as part of an actual command
- unlock cfn-lint as its releases include updates to the CloudFormation Specification that needs to keep up with what AWS has released
=> <fix> Unlock cfn-lint version

gen3-cli/cot/backend/create/unitlist/__init__.py, gen3-cli/cot/command/create/__init__.py, gen3-cli/cot/command/create/unitlist.py, gen3-cli/tests/unit/command/create/test_unitlist.py
supports the generation of the unitlist output which provides a list of deployment units for a given segment
This aligns with the outputs available from createTemplate at the moment
Tested locally and tests included in PR
=> feature: add unitlist generation command

gen3-cli/cot/command/create/blueprint.py, gen3-cli/cot/command/create/buildblueprint.py, gen3-cli/cot/command/create/template.py, gen3-cli/tests/unit/command/create/test_blueprint.py, gen3-cli/tests/unit/command/create/test_buildblueprint.py, gen3-cli/tests/unit/command/create/test_template.py
Removes these inputs to align with their remove from the bash executor
While scenarios and test cases still exist they have  been implemented inside of the engine rather than as external inputs. So their input parameters are no longer required
tested locally and in unit tests
=> fix: remove testcase and scenario inputs to align with bash

Jenkinsfile
Adds a build trigger to start the rebuild of the hamlet offical containers on updates to the master branch of this repo
Ensures our container images have the lastet version of the cli installed
Will be tested on automation server using this PR
=> feature: trigger hamlet builds from updates

hamlet-cli/hamlet/backend/test/run.py, hamlet-cli/hamlet/command/test/run.py, hamlet-cli/requirements/prod.txt, hamlet-cli/setup.py
Adds support for passing parameters directly to pytest when we run template testing
The main motivation for this is to generate junit test results which can be used in our CI process to show more detailed testing reports during the testing process
Tested locally
=> feat: support additonal pytest arguments on run

hamlet-cli/hamlet/__init__.py, hamlet-cli/hamlet/command/visual/__init__.py, hamlet-cli/tests/unit/command/visual/test_draw.py, hamlet-cli/tests/unit/command/visual/test_list.py
Initial CLI support for the diagrams plugin and its executor 
This provides a shortcut group to list and generate diagram files using hamlet. Future iterations will also generation the diagrams themselves
Tested locally
=> feat: add support for diagram plugin generation and execution

hamlet-cli/hamlet/command/common/display.py, hamlet-cli/tests/unit/command/query/test.py
Minor fix to support outputs from query commands which contain numbers
Currently when querying the attributes of a component which provided number outputs ( like a port ) the disaply command would fail
Tested locally
=> fix: allow for int outputs in tables

hamlet-cli/hamlet/command/deploy/__init__.py, hamlet-cli/hamlet/command/query/__init__.py
Minor change to fix the provider parameter across the different command groups to support multiple providers
The provider parameter was inconsistent 
Tested locally
=> fix: make provider input supoprt multiple

hamlet-cli/requirements/prod.txt, hamlet-cli/setup.py
Adds package dependencies required to use the diagram drawing executor as part of the diagrams provider
Allows for running digrams generation in the hamlet container
Tested locally
=> feat: add diagrams depdencies for visual

hamlet-cli/hamlet/backend/common/runner.py, hamlet-cli/hamlet/command/common/exceptions.py, hamlet-cli/hamlet/command/deploy/__init__.py, hamlet-cli/hamlet/command/entrance/__init__.py, hamlet-cli/hamlet/command/manage/credentials_crypto.py, hamlet-cli/hamlet/command/manage/crypto.py, hamlet-cli/hamlet/command/manage/deployment.py, hamlet-cli/hamlet/command/manage/file_crypto.py, hamlet-cli/hamlet/command/manage/stack.py, hamlet-cli/hamlet/command/run/expo_app_publish.py, hamlet-cli/hamlet/command/run/lambda_func.py, hamlet-cli/hamlet/command/run/pipeline.py, hamlet-cli/hamlet/command/run/sentry_release.py, hamlet-cli/hamlet/command/run/task.py, hamlet-cli/hamlet/command/visual/__init__.py
- Adds cleaner handling of exceptions raised from calls to the backend which have failed when called from the command line. 
Instead of a full stack trace along with the script STDERR we now show the following 
The error text will also be bolded red
- Adds support for running Azure deployments using the hamlet run-deployments command and also adds an exception if a provider isn't supported
While its bad that that the script fails the command itself hasn't really failed as an exception. So our handling of these exceptions should be to show the user what happened
Adding support for azure provides consistency with our offical providers and their use with the hamlet cli
Tested locally and through local test suite
=> feat: command exceptions and azure deploys

hamlet-cli/hamlet/command/generate/cmdb.py, hamlet-cli/tests/unit/command/generate/cmdb/test_account.py
Python executor implementation of https://github.com/hamlet-io/executor-cookiecutter/pull/10 
Aligns with recent updates to the engine which move to a more generic configuration of accounts
Note this has changed some of the command options for the hamlet generate cmdb account command 
- account-type = provider-type 
- aws-account-id = provider-id
=> feat(generate)!: support provider types in account

hamlet-cli/hamlet/backend/draw/diagram.py, hamlet-cli/hamlet/backend/draw/diagram_schema.py, hamlet-cli/hamlet/backend/draw/render.py, hamlet-cli/hamlet/command/visual/__init__.py, hamlet-cli/tests/unit/command/visual/test_draw.py, hamlet-cli/tests/unit/command/visual/test_list.py
Adds support for diagram generation as part of cli. This essentially merges the diagram generation script from https://github.com/hamlet-io/executor-diagrams and makes it available as a cli backend. The command will create the appropriate hamlet outputs, generate the diagram script and then execute the script to create the diagram. 
The output dir must be set at the moment as the cli doesn't know the CMDB output dirs during its processing 
Example
```bash
hamlet visual -i mock -p aws -p diagrams -p awsdiagrams draw-diagram --type overview -o ~/cmdb/testing/diagram_test/
```
Creates the following files 
```
/home/hamlet/cmdb/testing/diagram_test/
├── diagram-overview-config.json
├── diagram-overview-digaram.png
├── diagram-overview-generation-contract.json
└── diagram-overview-script.py …
```
=> feat: diagram generation from cli

hamlet-cli/hamlet/backend/query/__init__.py, hamlet-cli/hamlet/command/query/__init__.py, hamlet-cli/tests/unit/command/query/test.py
Updates the query commands to use the RawId when running queries. This Id reflects what is provided in the CMDB
Part of https://github.com/hamlet-io/executor-python/issues/70 
Tested locally
- Requires: https://github.com/hamlet-io/engine/pull/1539 which makes the RawId value available
=> refactor: use rawId in query outputs

hamlet-cli/hamlet/backend/manage/deployment/__init__.py
This allows for the run-deployments command to be executed from outputs not part of a CMDB
Fixes an issue where run-deployments was expecting the manage deployment script to provide output_dir
Tested locally
=> fix: add output_dir to manage deployment

hamlet-cli/hamlet/backend/draw/diagram.py, hamlet-cli/hamlet/backend/draw/render.py, hamlet-cli/hamlet/command/visual/__init__.py, hamlet-cli/tests/unit/command/visual/test_draw.py, hamlet-cli/tests/unit/command/visual/test_list.py
- Adds support for generating multiple diagrams from a single command and aligns with the user generated diagram approach. This uses the same approach as the deployments commands which query the available commands and apply regex filtering based on the provided id
- Adds a list diagrams command to show the available commands
- Splits the output directories for source code and the generated diagram images. This allows for users to decide on what they require and where they can store each output type
Makes the diagram generation process easier when a number of diagrams have been defined and also allows for automated processes to easily update the solution diagrams as required
- The existing draw-diagram command has been replaced with draw-diagrams and the …
=> feat: multiple diagram generation

hamlet-cli/README.md
I recently deleted this README so we only had to maintain the one for this repo.
However the setup.py script uses the readme to write its package docuementation.
This creates the file as a symbolic link to the main README file.
Broke the docker build
n/a
=> fix: recreate child readme as symlink

hamlet-cli/hamlet/__init__.py, hamlet-cli/hamlet/backend/setup/__init__.py, hamlet-cli/hamlet/command/setup/__init__.py
Adds the ${GENERATION_DIR}/setup.sh command from the bash executor into the cli
This command is currently used for installing the required plugins defined in a CMDB. This makes it easy to manage the plugin and setup installation process
Tested locally
=> feat: setup command

hamlet-cli/hamlet/command/common/config.py, hamlet-cli/hamlet/command/common/decorators.py
- adds the root_dir to the common district configuration
- linting fixes in files related to this configuration option
This is a common configuration option and is required when working outside of a cmdb directory 
Tested locally and using test suite
=> feat: add root_dir as common option

hamlet-cli/hamlet/command/generate/product.py
Fixes #91 - Which will pass the output_dir down to the cookiecutter util as part of the **kwargs catch all parameter on the command function. 
Generation of template was failing
=> fix: output_dir paramter not required

hamlet-cli/hamlet/backend/manage/credential_crypto/__init__.py, hamlet-cli/hamlet/backend/manage/crypto/__init__.py, hamlet-cli/hamlet/backend/manage/deployment/__init__.py, hamlet-cli/hamlet/backend/manage/file_crypto/__init__.py, hamlet-cli/hamlet/backend/manage/stack/__init__.py, hamlet-cli/hamlet/command/deploy/__init__.py, hamlet-cli/hamlet/command/manage/credentials_crypto.py, hamlet-cli/hamlet/command/manage/crypto.py, hamlet-cli/hamlet/command/manage/deployment.py, hamlet-cli/hamlet/command/manage/file_crypto.py, hamlet-cli/hamlet/command/manage/stack.py, hamlet-cli/tests/unit/command/deploy/test_deploy.py, hamlet-cli/tests/unit/command/deploy/test_list.py
Adds support for filtering deployments based on their current state. 
Includes run-deployment handling for remove orphan deployments as part of the process. This will skip template generation and show a warning message if an orphan resource is being processed as part of deployment run 
All of the deploy group command now includes a new option -s/--deployment-state which defaults to `deployed` and `notdeployed`. This aligns with the current state of the deployment processing 
On list and run there is an additional state value called `orphaned` which can be used to show deployments which shouldn't be active and allows you to perform cleanups as required
Also adds env options to the manage commands as this was missed before.
Implements https://github.com/hamlet-io/engine/pull/1574 for the …
=> feat: Deployment state support

hamlet-cli/hamlet/__init__.py, hamlet-cli/hamlet/backend/query/__init__.py, hamlet-cli/hamlet/command/common/display.py, hamlet-cli/hamlet/command/component/__init__.py, hamlet-cli/hamlet/command/component/common.py, hamlet-cli/hamlet/command/component/describe_occurrence.py, hamlet-cli/hamlet/command/component/list_occurrences.py, hamlet-cli/tests/unit/command/component/test_occurrence.py
Uses the occurrence entrance from  to list and describe occurrences which are part of a hamlet district. The new commands belong to a new group called component which focuses on information about components 
- `hamlet component list-occurrences` shows all of the occurrences with their TierId, ComponentId, Name and Type available as outputs. The --query option on this parameter allows for filtering the output using JMESPath 
- `hamlet component describe-occurrence` provides the full occurrence output for a named occurrence. The Name field from the list occurrences command is used as the filter key. 
- The --query option allows for filtering the output using JMESPath 
- Subcommands `solution`, `attributes`, `resources`, `setting-namesspaces` are predefined JMESPath queries which can be used …
=> feat: Component command group

hamlet-cli/hamlet/backend/common/shell_vars_to_json.py, hamlet-cli/hamlet/backend/test/run.py, hamlet-cli/tests/conftest.py
- When making call to bash from the cli ensure that we use an installed version using the equivalent of where for python
- Fixes an issue in testing where the cmdb root dir doesn't exist
Ensures the cli works across different operating systems and installations
=> refactor: find available bash install when calling

hamlet-cli/hamlet/command/deploy/__init__.py
Fixes the logic to skip output generation on orphaned outputs
We can't generate orphaned outputs as they don't exist in the cmdb anymore
tested locally
=> fix: skip refresh for orphaned deployments

CHANGELOG.md, package.json
fix the url referenced in changelogs to align with each repo
Makes the changelog understandable
Tested locally
=> fix: repo url in changelogs

.github/workflows/release.yml, .github/workflows/testing.yml, hamlet-cli/requirements/dev.txt
Adds automated support for releasing the cli to pypi 
Releases the latest version of the hamlet cli to pypi on push and release tagging
Testing with PR
=> feat: add relesae support for cli

.github/workflows/release.yml
Github actions can't push to protected branches, which is understandable. So instead we raise a PR against master 
bump the version via PR to keep it aligned with whats in pypi 
Will test on merge
=> fix: use pull release for version bump

.github/workflows/release.yml, hamlet-cli/.bumpversion.cfg, hamlet-cli/setup.py
Adds a pre-release tagging strategy which will allow for building and publishing master commits as prereleases in pypi.
When a tag is applied to the repo then a normal package update will go through and make the release available in pypi 
This is a cleaner strategy and allows us to have the latest docker image with the prerelease of the package and other docker releases can be aligned with the image that suits 
Will test with PR and deploy process
=> Refactor prerelease master

hamlet-cli/hamlet/backend/common/runner.py, hamlet-cli/hamlet/command/deploy/list.py
- forwards logs when using cli mode to stdout and use this output to show exception details when the engine fails to run
- fixes missing imports for displaying the deployments list
Quality of life changes to provide details of failures from the engine when the happen 
- None
- None
- None
=> fix: log engine fatal messages on failure

hamlet-cli/hamlet/command/component/describe_occurrence.py, hamlet-cli/hamlet/command/component/list_occurrences.py, hamlet-cli/tests/unit/command/component/test_occurrence.py
Uses the rawId and Name values when dealing with occurrence queries this ensures that occurrences have uniqiue ids so that each one can be queried
Fixes #117 
- https://github.com/hamlet-io/engine/pull/1658
- None
- None
=> feat: use raw name and id for occurrences

hamlet-cli/hamlet/backend/manage/deployment/__init__.py, hamlet-cli/hamlet/command/deploy/create.py, hamlet-cli/hamlet/command/deploy/list.py, hamlet-cli/hamlet/command/deploy/run.py, hamlet-cli/tests/unit/command/deploy/test_deploy.py
- Documentation (new or update to existing)
- Breaking change (fix or feature that would cause existing functionality to change)
- Adds the ability to run a dry run before executing a deployment. This will submit the deployment to a providers service which will show the difference between the current deployment and the submitted deployment
Example for an AWS deployment
```bash 
hamlet --profile msw deploy run-deployments --dryrun --confirm -u instance
```
```bash
[*] solution/instance
(Info) Generating outputs:
[*] entrance: deployment | output: contract | subset: …
```
=> feat: add dryrun tasks to run deployment

.github/workflows/release.yml
Uses Githubs event for a created release to trigger tag based releases.
The current approach sees the master branch and bumps the version but doesn't trigger the release step when a tag is pushed 
Will be tested with this PR
- None
- None
- None
=> fix: run release versions based on created release

.github/workflows/release.yml, hamlet-cli/.bumpversion.cfg, hamlet-cli/setup.py
On tag releases bump to the next patch automatically to allow for continual pre-releases
This allows for ongoing development between releases. The tag applied on a release will set the semver compliance but between development stages we reset to the next minor version
- None
- None
- None
=> fix: bump release to next dev release

hamlet-cli/MANIFEST.in
Fixes an issue where the generate cookie cutter templates weren't included in the python package
Generate commands were failing when using the pip package
Tested locally outside of the edit pip install mode
- None
- None
- None
=> fix: include cookie cutter templates in package

hamlet-cli/hamlet/backend/common/runner.py, hamlet-cli/setup.py
- adds a fix for the command runner to ensure that we collect and report outputs on exceptions. The stdout and stderr are split as its difficult to merge them. But this at least makes output visible
- fix for networkx install requirements which were breaking with changes between cfn-lint and networkx
The main motivation for the logging updates is to make it easier to understand where something has gone wrong in hamlet without having to run alternative commands 
- None
- None
- None
=> fix: logging during cli execptions and package deps

hamlet-cli/hamlet/__init__.py, hamlet-cli/hamlet/backend/common/runner.py, hamlet-cli/hamlet/backend/container_registry/__init__.py, hamlet-cli/hamlet/backend/create/template/__init__.py, hamlet-cli/hamlet/backend/engine/__init__.py, hamlet-cli/hamlet/backend/engine/common.py, hamlet-cli/hamlet/backend/engine/engine.py, hamlet-cli/hamlet/backend/engine/engine_loader.py, hamlet-cli/hamlet/backend/engine/engine_part.py, hamlet-cli/hamlet/backend/engine/engine_source.py, hamlet-cli/hamlet/backend/query/__init__.py, hamlet-cli/hamlet/backend/run/expo_app_publish/__init__.py, hamlet-cli/hamlet/backend/run/lambda_func/__init__.py, hamlet-cli/hamlet/backend/run/pipeline/__init__.py, hamlet-cli/hamlet/backend/run/sentry_release/__init__.py, hamlet-cli/hamlet/backend/run/task/__init__.py, hamlet-cli/hamlet/command/__init__.py, hamlet-cli/hamlet/command/common/config.py, hamlet-cli/hamlet/command/common/decorators.py, hamlet-cli/hamlet/command/engine/__init__.py, hamlet-cli/hamlet/command/setup/__init__.py, hamlet-cli/hamlet/env.py, hamlet-cli/setup.py, hamlet-cli/tests/unit/backend/engine/test_engine.py, hamlet-cli/tests/unit/command/engine/test_engine.py
Adds support for managing hamlet engine installations through the cli. This allows for installing and setting a default engine to use along with installing and managing different engine installations 
At the core of this process is the EngineStore, which is a collection of engines that can be used by the hamlet cli and executors. 
Each Engine is made up of two components, Parts and Sources 
- Sources define external locations to retrieve the engine code from. The initial implementation supports an container registry pull which pulls the images based on the V2 docker registry API 
- Parts map the sources to defined hamlet components, these map to the different parts of hamlet that make up the overall engine and have a link to a …
=> feat: engine management

hamlet-cli/hamlet/command/deploy/run.py
Allow dry runs to be run for all operations from the cli perspective
with https://github.com/hamlet-io/executor-bash/pull/223 the aws provider now supports dry run actions for create actions. This filter was stopping that from happening. 
- None
- None
- None
=> feat: allow dryn runs on create  actions

hamlet-cli/hamlet/backend/engine/__init__.py, hamlet-cli/hamlet/backend/engine/common.py, hamlet-cli/hamlet/backend/engine/engine.py, hamlet-cli/hamlet/backend/engine/engine_loader.py, hamlet-cli/hamlet/command/__init__.py, hamlet-cli/hamlet/command/common/config.py, hamlet-cli/hamlet/command/common/decorators.py, hamlet-cli/hamlet/command/common/engine_setup.py, hamlet-cli/hamlet/command/engine/__init__.py, hamlet-cli/tests/unit/command/engine/test_engine.py
- Adds support for detecting and install updates to engines. By default the cli will check for updates on each command 
run and install the update or warn that one is available for the currently selected engine.
- Adds a check in hamlet engine list-engines to show available updates
- Disabling auto update is available through the root command, env varor profile. env var = HAMLET_UPDATE_ENGINE, and auto-update-engine isavailable for the profile and cli
- Adds the tram engine loader which is a tested nightly build of the offical hamlet components
- Fixes an issue where the hamlet home dir didn't exist when installing engines
The main motivation for this feature is to allow users to see if a new hamlet engine is available and have …
=> feat: add support for engine updates

hamlet-cli/.bumpversion.cfg, hamlet-cli/hamlet/__about__.py, hamlet-cli/hamlet/command/__init__.py, hamlet-cli/setup.py
- Adds the --version flag to the root hamlet command which shows the current running version of the hamlet cli
- Moves the version details to a file which can be imported into other modules
Pretty straightforward at the moment 
```
hamlet --version 
hamlet, version 8.2.0-dev12
```
Fixes #158  to allow for debugging and troubleshooting across different installations 
- None
- None
- None
=> feat: include cli version in command

hamlet-cli/hamlet/command/visual/__init__.py
provides the full options stack to the query used to find diagrams instead of the older generation context
Diagram listing would fail if the account was set through the hamlet cli options
- None
- None
- None
=> fix: options passed to backend query for diagrams

hamlet-cli/hamlet/__about__.py, hamlet-cli/hamlet/backend/engine/engine_source.py, hamlet-cli/hamlet/command/engine/__init__.py, hamlet-cli/tests/unit/command/engine/test_engine.py
Adds two new commands to the engine command group 
- describe-engine - provides a detailed description of an engine including its current state and the state of the parts and sources that make up the engine 
- add-engine-source-build - Is used to create a hamlet_source.json file which locates key details about how the code of a repo was built that will be used as a source. This is intended to be run as part of the build of engine sources so that we can query them to find out where the code came from 
The describe engine command allows for detailed information when troubleshooting issues and allows people to see what engine sources are currently being used.
Tested locally
- None
- None
- None
=> feat: detailed engine information

hamlet/command/__init__.py, hamlet/command/common/engine_setup.py, hamlet/command/engine/__init__.py
- always install the global engine regardless of auto update process
- only run auto engine installs when not in the engine subcommand
- always set the engine env
- add some extra echos for user info
fixes #175  and makes sure the global engine is always available for explicit set commands run at the start of a hamlet session
- None
- None
- None
=> fix: handle  installation process and global env

hamlet/backend/engine/__init__.py, hamlet/backend/engine/engine.py, hamlet/backend/engine/engine_loader.py, hamlet/backend/engine/exceptions.py, hamlet/command/__init__.py, hamlet/command/common/engine_setup.py, hamlet/command/engine/__init__.py
- add support for reinstalling the global engine if it is not the same state version as the one expected by the cli
- add new exception case so that we can handle invalid engines
- add warning that you might loose an old engine if it can't be found after being cleaned
- moves clean functions to the engine_store for wider usage across engine handling
The main motivation here is to make it easy to manage engine versions and allow for the cli to handle as much of the version management for engines possible without requiring too much effort. 
Tested locally
- None
- None
- None
=> feat: handle out of date global engine

setup.py
removes an unrequired dependency on networkx which is used by cfn-lint and another package. This was causing issues on import that have been fixed in version 0.25.0 of the cli
removes fixed dependency that we didn't need
tested locally
- None
- None
- None
=> refactor: remove networkx fixed dependecy

hamlet/backend/engine/engine_loader.py
adds the wrapper engine part into the tram engine definition. Now that the wrapper has been included in the unicycle release its available for use in the tram releases
Adding the wrapper means that both our stable and unstable engines use the dedicated package for the wrapper instead of relying on one in the source code
Tested locally
- None
- None
- None
=> feat(engine): add the wrapper into the tram

hamlet/backend/container_registry/__init__.py, hamlet/backend/engine/engine_source.py, setup.py, tests/unit/backend/engine/test_engine.py
- replaces requests with httpx which is the successor to requests
- refactors the container repository process into a self contained class
which manages detailing with container registries
- Adds support for getting the tags of a container repository
The main motivation was to separate dealing with the container registry from the container source and to use clients to increase network performance and authentication handling 
Adding tag returns allows us to add multiple engines for tags available on a container
Tested locally and with testing suite
- None
- None
- None
=> feat: container tags and repository refactor

hamlet/backend/container_registry/__init__.py, hamlet/backend/deploy/__init__.py, hamlet/backend/engine/__init__.py, hamlet/backend/engine/engine.py, hamlet/backend/engine/engine_code_source.py, hamlet/backend/engine/engine_loader.py, hamlet/backend/engine/engine_source.py, hamlet/backend/engine/exceptions.py, hamlet/command/common/engine_setup.py, hamlet/command/deploy/run.py, hamlet/command/engine/__init__.py, setup.py, tests/unit/backend/engine/test_engine.py, tests/unit/command/deploy/test_test.py, tests/unit/command/engine/test_engine.py
- Adds support for showing the hidden engines in the cli 
- Adds dynamic lookup loaders for both tram and train releases 
- The trams are the nightly builds of offical hamlet engine and are named based on the date they were created
- The trains are defined releases that have been marked for release by a maintainer. They are named using semver
- fixes an issue in the build data collection which resulted in only one build source being shown
This makes our release process feature complete  at this point in time and allows us to manage hamlet engine releases via the cli. 
- None
- None
- None
=> feat: hidden engines and dynamic loaders

hamlet/backend/engine/engine_loader.py
- Use edge instead of latest for the unicycle release tags to align with the tagging used on the repos and whats provided through the docker metadata process
- Use schedule instead of tram for the tag lookup on the base repo to align with docker metadata naming 
Align our docker tags with the standards to make them easier to follow
- None
- None
- None
=> refactor(engine): align unicycle docker tags

hamlet/backend/engine/__init__.py, hamlet/backend/engine/engine.py, hamlet/backend/engine/engine_loader.py, hamlet/backend/engine/engine_source.py, hamlet/command/__init__.py, hamlet/command/common/config.py, hamlet/command/common/decorators.py, hamlet/command/common/engine_setup.py, hamlet/command/engine/__init__.py, hamlet/command/query/__init__.py, tests/unit/backend/engine/test_engine.py, tests/unit/command/engine/test_engine.py
A collection of updates and features to make update handling easier in the cli 
- limit how often the engines are loaded from external sources
- add a local list which will act as the default engine between the
cache timeouts
- limit how often digests are checked to determine updates
- handle missing engines when checking for updates and setting up the
global engine
- Allow for updating engines automatically when update detected
- Allow the user to define the update check interval
- Adds two levels of engines local and external which control the engine
loading process
- Updates the …
=> refactor: updating handling for engines

hamlet/command/component/describe_occurrence.py, hamlet/command/component/list_occurrences.py, tests/unit/command/component/test_occurrence.py
Use `TypedRawName` rather than `RawName` in the occurrence structure.
Avoid name clashes for subcomponents with the same identifiers.
Fixes #197 
Local command execution.
- https://github.com/hamlet-io/engine/pull/1725
- None
- None
=> refactor: component commands

hamlet/command/common/engine_setup.py
shows the name of the default global engine which will be installed when an engine is missing
Minor regression with the changes from #174 
Tested locally
- None
- None
- None
=> fix: default engine notification during install

hamlet/command/__init__.py, hamlet/command/common/engine_setup.py
- adds handling of engines set through environment variable which haven't been installed.
- If the global engine hasn't been set already use the env var as the global engine
When setting the HAMLET_ENGINE env var to define the hamlet engine you want to use. If the engine wasn't installed the command would fail to setup the environment. 
Setting the environment variable will be common in CI environments so this needs to handle the install process automatically 
- None
- None
- None
=> fix: handle engine set via env var

hamlet/command/__init__.py, hamlet/command/common/decorators.py, hamlet/command/component/__init__.py, hamlet/command/deploy/__init__.py, hamlet/command/engine/__init__.py, hamlet/command/entrance/__init__.py, hamlet/command/generate/__init__.py, hamlet/command/generate/cmdb.py, hamlet/command/manage/__init__.py, hamlet/command/release/__init__.py, hamlet/command/run/__init__.py, hamlet/command/schema/__init__.py, hamlet/command/test/__init__.py, hamlet/command/visual/__init__.py
- makes the env var available in help to configure root level configuration options to make it easier to define these values
- ensures that the same screen width is used across all commands and groups to make help output readable
- removes env var options on subcommands and groups to make a consistent approach to running commands
Makes it easier to find configuration options for users and to understand how the environment works 
remove the env var options provides a consistent approach and makes commands easier to understand where their config came from. The exception here is the root commands which often configure the CLI overall 
- None
- None
- None
=> feat: show envvars for root command options

hamlet/backend/engine/common.py
Makes the train engine the default engine selected if no other global engines are found
Moves the cli to use a more stable release of hamlet by default
- None
- None
- None
=> feat: make the train engine the default global engine

CONTRIBUTING.md, Makefile, README.md, hamlet/__about__.py
renames the setup.py package from hamlet-cli to hamlet
The existing package will be updated to handle this migration once the new package is published
Creates a cleaner package name and highlights that the package also contains services other than the hamlet cli. You can use the backends if you want to
Tested on deploy
- None
- None
- None
=> feat: rename hamlet package

hamlet/command/engine/__init__.py, tests/unit/command/engine/test_engine.py
Adds more control over what happens when the install command is run to prevent unnecessary work
Adds a command to get the current engine and output as a string
Aligns the input for the all engine commands which require an engine name to use an argument instead of an option
This makes it easy to perform engine management within CI pipelines to reduce the number of things done during the pipeline. This ensures that we don't have create unexpected dependencies on external services 
- None
- None
- None
=> feat: engine install control and get engine

hamlet/backend/deploy/__init__.py, hamlet/command/deploy/create.py, hamlet/command/deploy/list.py, hamlet/command/deploy/run.py, hamlet/command/deploy/test.py, tests/unit/command/deploy/test_deploy.py, tests/unit/command/deploy/test_list.py, tests/unit/command/deploy/test_test.py
- Adds the ability to filter deployments based on their district
- sets a default district filter as segment to maintain the existing behaviour
This allows for controlling all available deployments from the cli
- None
- None
- None
=> feat: add district based deployment filters

hamlet/backend/automation_tasks/transfer_image/__init__.py, hamlet/backend/automation_tasks/upload_image/__init__.py
Adds the provided user params for automation tasks through to the automation context instead of just to the command that needs them
Errors were being raised during the automation set context as some required these env vars
tested locally
- None
- None
- None
=> fix: provide details to set context for automation

hamlet/backend/automation_tasks/base.py, hamlet/backend/automation_tasks/transfer_image/__init__.py, hamlet/backend/automation_tasks/update_build/__init__.py, hamlet/backend/automation_tasks/upload_image/__init__.py, tests/unit/backend/automation_tasks/test_automation_runner.py
- Removes running the properties lookup process from all automation runner commands
- Handle scripts which return output during automation tasks
All of the automation tasks that the cli wraps require the properties generated by the get_properties function. Removing it from the default implementation of the task runner reduces the steps required to complete a task
tested locally
- None
- None
- None
=> refactor: automation properties

hamlet/command/component/__init__.py, hamlet/command/component/query_occurrences.py, tests/unit/command/component/test_occurrence.py
- Adds a command to run JMESPath queries across all occurrences found in a given district
This is an extension on the current describe-occurrence command which allows you to find out detailed information on a given occurrence. The query-occurrences command requires a JMESPath query which it runs over the full array of occurrences 
- None
- None
- None
=> feat: add occurrences query

hamlet/__init__.py, hamlet/backend/automation/save_cmdb_repos/__init__.py, hamlet/backend/automation_tasks/save_repos/__init__.py, hamlet/backend/common/runner.py, hamlet/command/cmdb/__init__.py
Adds a CMDB command to save the state of all repositories
This allows you to save a batch of changes performed across the CMDBS as a single command without having to know the directories where the CMDBS are
Tested locally
- https://github.com/hamlet-io/executor-bash/pull/273
- None
- None
=> feat: add cmdb save command

hamlet/backend/container_registry/__init__.py, hamlet/command/__init__.py
Add exception handling for when updates can not be checked through the container registry
If an external container registry is having issues hamlet commands cannot be run 
Tested locally
- None
- None
- None
=> fix: handle container registry update failures

hamlet/backend/automation/set_automation_context/__init__.py, hamlet/backend/automation_tasks/save_repos/__init__.py, hamlet/backend/automation_tasks/transfer_image/__init__.py, hamlet/backend/automation_tasks/update_build/__init__.py, hamlet/backend/automation_tasks/upload_image/__init__.py
- Fixes the order of automation tasks when determining the context that a provided command is running in. Allowing for either directory based context or cli context to be used
- Includes support for disabling the automation credentials lookup when not required
These updates align with the idea that you can use either the directory context or the cli context
Tested locally
https://github.com/hamlet-io/executor-bash/pull/280 
- None
- None
- None
=> fix: determine tree before context

MANIFEST.in, hamlet/command/__init__.py, hamlet/command/common/config.py, hamlet/command/common/decorators.py, hamlet/command/common/engine_setup.py, setup-hamlet.sh, setup.py
removes the auto update process and replaces it with a post install script for the cli to update the engine when a new version of the cli is installed
On install of the hamlet cli a post install script will install at least one version of the hamlet cli and when installing a new version of the cli it will automatically update the current global engine. This ensures that the cli is compatible with the latest changes if there are any for that release.
If the global engine isn't set the current engine details will be used to install an engine and set it to the global engine
The update checking process was slowing down the command running and producing unreliable output when running commands. …
=> refactor: remove updating checking

hamlet/command/__init__.py, hamlet/command/common/exceptions.py, hamlet/utils/__init__.py
Changes the home dir write checking to be fatal instead of a large warning
Now that engines are being used by most people to manage their access to hamlet dev resources the home dir is essentially required for all hamlet commands. Making this fatal simplifies the error processing and makes it easier to understand what needs to be done
Tested locally and with test suite 
- None
- None
- None
=> refactor: make missing home dir fatal

hamlet/backend/common/context.py, hamlet/backend/query/__init__.py, hamlet/env.py
moves the cli cache dir from saving in root_dirs over to saving into a local cli cache
Removes files that aren't required in the CMDB out of the CMDB and to an appropriate place 
- None
- None
- None
=> refactor: move the cli cache dir to hamlet home

hamlet/backend/engine/__init__.py, hamlet/command/common/engine_setup.py, hamlet/command/engine/__init__.py
- Instead off installing the engine when running set-engine now require it to be installed before this can happen.
- Updates exception messages to provide details on how to fix an engine lookup issue
Makes it easier to understand the setup process and to align with the idea that there should be one way to do things
- None
- None
- None
=> fix: require install of engine before set

hamlet/backend/common/runner.py
fixes the preference order for environment variables when running backend tasks
Makes the most specific env var parameters i.e. the ones provided by hamlet cli itself the preferred values to use when passing commands to the runner. This mainly fixes an issue where overrides performed during the automation processing were being overridden by the os environment variables
- None
- None
- None
=> fix: env preference order for runner

hamlet/backend/create/template/context_tree.py, tests/integration/backend/create/template/test_context_tree.py
- Updates the usage of account infrastructure dir to use state instead
Aligns with the changes in https://github.com/hamlet-io/executor-bash/pull/299
Tested locally and with test suite 
- None
- None
- None
=> refactor: align account infra to state dir

hamlet/__init__.py, hamlet/command/component/__init__.py, hamlet/command/component/component_types.py, hamlet/command/layer/__init__.py, tests/unit/command/component/test_component_types.py, tests/unit/command/layer/test_describe.py, tests/unit/command/layer/test_list.py, tests/unit/command/layer/test_query.py
- Adds support for querying the available layer data
- Adds support for querying the component types that are available along with their attributes
Makes it possible to query the resulting properties of layers and component types. To know what properties and data is available 
Tested locally and included test cases 
- None
- None
- None
=> feat: add layer and component type info

tests/integration/backend/create/template/test_context_tree.py, tests/integration/backend/create/template/test_set_context.py, tests/integration/backend/test/test_utils.py, tests/unit/backend/common/test_context.py, tests/unit/backend/common/test_fsutils.py, tests/unit/command/manage/test_credentials_crypto.py, tests/unit/command/manage/test_crypto.py, tests/unit/command/manage/test_file_crypto.py
- replace os.mknod the open() method to allow for support on OSX based machines
OSX requires escalated privileges for mknod for creating files so using a standard file open removes this requirement
- None
- #262 
- None
=> refactor: osx support for testing

hamlet/backend/common/runner.py, hamlet/command/run/task.py
- Ensure that options passed to bash scripts are quoted to ensure spaces aren't treated as breaks
Running a script with a spaced option value in a list of multiple values would cause the script to fail
- None
- None
- None
=> fix: quoting for shell params

hamlet/backend/create/template/__init__.py, hamlet/backend/query/__init__.py, hamlet/command/entrance/__init__.py, hamlet/command/schema/__init__.py, tests/unit/command/component/test_component_types.py, tests/unit/command/component/test_occurrence.py, tests/unit/command/deploy/test_deploy.py, tests/unit/command/deploy/test_list.py, tests/unit/command/deploy/test_test.py, tests/unit/command/entrance/test_invoke.py, tests/unit/command/entrance/test_list.py, tests/unit/command/layer/test_describe.py, tests/unit/command/layer/test_list.py, tests/unit/command/layer/test_query.py, tests/unit/command/reference/test_describe.py, tests/unit/command/reference/test_list.py, tests/unit/command/reference/test_query.py, tests/unit/command/schema/test_create.py, tests/unit/command/schema/test_list.py, tests/unit/command/visual/test_draw.py, tests/unit/command/visual/test_list.py
- Adds support for providing entrance parameters to create template
- Updates testing to support new args for create template
- refactors some of the deploy testing to test appropriate task calls
More entrances are now using the entrance parameters instead of overloading the deployment Unit and Group standard entrance parameters. This allows for the cli to support these entrances
- None
- None
- None
=> feat: add entrance parameter support

hamlet/__init__.py, hamlet/command/__init__.py, hamlet/command/task/__init__.py, tests/unit/command/task/test_describe.py, tests/unit/command/task/test_list.py, tests/unit/command/task/test_run.py
- Adds the task command group for task and contract related activities
- Adds runbook execution and listing of runbooks
- Adds testing for the commands
The runbook name is based on the RawTypedName of the run book with runbook inputs provided through space separated key value arguments 
```bash
hamlet task run-runbook -n my-runbook runbookInput1="this" runbookInput2="that" 
```
This allows for generating and running runbooks through the hamlet cli which makes them easy to discover and run 
- None
- https://github.com/hamlet-io/executor-python/pull/276
- None
=> feat: add support for runbook execution through cli

hamlet/backend/container_registry/__init__.py, hamlet/backend/engine/loaders/tram.py, setup.py
- Adds support for paginated responses from tag listing
- Updates the httpx client to the latest version
- Adds automatic retries on calls to the container registry
The docker registry v2 api requires pagination for tag listing, if not managed the result is trimmed and you don't see all tags. 
Automatic retries help manage calls to the GHCR container registry which seems to limit or have issues every now and again
- None
- None
- None
=> fix: pagination for container tags

hamlet/backend/engine/__init__.py, hamlet/command/__init__.py, hamlet/command/engine/__init__.py, tests/unit/command/engine/test_engine.py
- Handles installing an engine defined through the override process
- Adds either argument or option for install engines
- Add global engine unset if engines are cleaned
- Fix digest details in engine install
In CI pipelines its common to set a global variable in the pipeline for configuration options. In hamlet you can set the engine this way using the HAMLET_ENGINE var, however if you are installing the engine you have set after setting this variable an error is raised that its not installed. 
This fixes that infinite loop problem and allows for installing engines which aren't available when an engine override is set.
Tested locally
- None
- None
- None
=> fix: engine override install process

hamlet/backend/contract/__init__.py, hamlet/backend/contract/tasks/aws_ecs_run_command/__init__.py, hamlet/backend/contract/tasks/aws_kms_decrypt_ciphertext/__init__.py, hamlet/backend/contract/tasks/aws_kms_encrypt_value/__init__.py, hamlet/backend/contract/tasks/conditional_stage_skip/__init__.py, hamlet/backend/contract/tasks/file_read_content/__init__.py, hamlet/backend/contract/tasks/output_echo/__init__.py, hamlet/command/common/validate.py, hamlet/command/entrance/__init__.py, hamlet/command/task/__init__.py, tests/unit/command/entrance/test_invoke.py, tests/unit/command/task/test_run.py
- Adds new contract tasks to handle encryption of values using kms and support for echoing output from other results
- fixes an issue in using conditional tasks
- Adds support for silent output on runbooks to only capture the output from tasks instead of extra details that show what the runbook is doing
- Adds validation of runbook parameters to split inputs on the first = only
Allows for the replacement of the current bash based scripts for encryption and allows for these to be included in custom runbooks as required.
- None
- None
- None
=> feat(contract): add kms encryption tasks

hamlet/command/common/engine_setup.py
- Fixes an issue where an engine installed as part of setting the default engine isn't found by the command running it
When an engine override is provided and no engines have been set as the global engine, the engine is automatically installed and setup. However  the available engines wern't being refreshed which meant that environment lookup was failing to find the engine.
Tested locally
- None
- None
- None
=> fix: initial engine loading missing engine

hamlet/backend/common/utilities.py, hamlet/backend/contract/tasks/aws_ecs_run_task/__init__.py
- Adds support for running an ecs task and waiting for its result
Migration of run*.sh scripts into runbook tasks to make it easier to define and execute the runbook within the hamlet context.
Tested locally
- None
- None
- None
=> feat: add support for ecs run task

hamlet/backend/create/template/__init__.py, hamlet/backend/manage/credential_crypto/__init__.py, hamlet/backend/manage/crypto/__init__.py, hamlet/backend/manage/deployment/__init__.py, hamlet/backend/manage/file_crypto/__init__.py, hamlet/backend/manage/stack/__init__.py, hamlet/backend/run/expo_app_publish/__init__.py, hamlet/backend/run/lambda_func/__init__.py, hamlet/backend/run/pipeline/__init__.py, hamlet/backend/run/sentry_release/__init__.py, hamlet/backend/run/task/__init__.py, hamlet/backend/setup/__init__.py, hamlet/backend/unitlist/__init__.py, hamlet/command/common/config.py, hamlet/command/common/decorators.py
- Adds support for controlling the log format ( full, compact ) used for createTemplate commands
Makes it easy to define the log format across all cli calls
Tested locally
- None
- None
- None
=> feat: log formattng control

hamlet/command/engine/__init__.py
- when an engine name isn't provided to the install-engine command it falls back to an engine provided via the root options
- When this happens the name of the engine needs to be provided instead of the engine itself
Command failing when running hamlet engine install-engine without the engine name provided as an argument
TEsted locally
- None
- None
- None
=> fix: engine name provided to install-engine

hamlet/backend/container_registry/__init__.py
- tight read timeout is used by default for httpx clients
- extending the timeout ensures we don't get read time out errors
Timeouts on downloading the large engine container images
Tested locally
- None
- None
- None
=> fix: extend read timeout for container image handling

hamlet/backend/contract/tasks/aws_ecs_run_task/__init__.py
- Always requires a ContainerName to be provided which will be used to determine the status of the task execution
- Adds error handling if the container provided doesn't return a 0 exit code
- Removes status logs and moves the output to the output. This can be then be used with an echo output for details
- Removes the option to wait or not from the task and instead always wait for the task to enter a stopped state
This makes it easier to follow what the task does and ensures that issues are captured and reported within the task process
Tested locally
- #322 
- None
- None
=> refactor: aws ecs run task error handling

hamlet/backend/engine/loaders/unicycle.py
- Reverts to using the full engine-core image instead of the platform specific image
At the moment the unicycle engine feeds the tram engine which feeds the train engine. So in order to ensure that the tram and train releases contain all possible platforms in their images we need to include all platforms in the unicycle build. 
This can be revisited in the future to work with an potential performance issues. 
Tested locally
- None
- None
- None
=> fix: use full engine-core image

hamlet/backend/engine/__init__.py, hamlet/backend/engine/loaders/shim.py
- adds a new shim engine that will be used when working with bundled installations of the engine core
Allows for supporting the legacy direct bash calling method with the newer bundled cli 
Tested locally
- None
- None
- None
=> feat: add bundled shim engine loader

hamlet/backend/engine/loaders/train.py, setup.py
- Adds support for migrating between the bundled engine wrapper and the local engine wrapper depending on the version of engine being used
Starting from hamlet 8.5.0 the bundled wrapper is the preferred way of working with hamlet. This adds support for that in the cli and automatically switches the engine part based on the version
Tested locally
- None
- None
- None
=> feat: add support for bundled engine train releases

hamlet/backend/contract/__init__.py, hamlet/command/common/config.py, hamlet/command/common/decorators.py, hamlet/command/task/__init__.py
- reinstates the hamlet_home_dir option that is used for a shared location for persistent data between command calls.
This was removed in  a recent change and the impact wasn't found until a bash script was run which required the env var to be set. 
- None
- None
- None
=> fix: add hamlet_home_dir back to base options

hamlet/backend/contract/tasks/aws_s3_download_bucket/__init__.py, hamlet/backend/contract/tasks/aws_s3_empty_bucket/__init__.py
- adds tasks for aws s3 related actions
- emptying a bucket included versions
- Copying the contents of a bucket locally
Allows for managing objects stored in s3 buckets
Tested locally
- None
- None
- None
=> feat: aws s3 copy rm tasks

hamlet/backend/contract/__init__.py, hamlet/backend/contract/tasks/aws_kms_decrypt_ciphertext/__init__.py, hamlet/backend/contract/tasks/aws_ses_smtp_password/__init__.py
- Adds a task to calculate an SMTP password from AWS access key
- Fixes comparison check of decryption
- Fixes support for boolean parameters on tasks.
Executor implementation of https://github.com/hamlet-io/engine-plugin-aws/pull/563
Tested locally
- None
- None
- None
=> feat: add contract task for SES SMTP password generation

hamlet/command/manage/credentials_crypto.py, hamlet/command/manage/crypto.py, hamlet/command/manage/deployment.py, hamlet/command/manage/file_crypto.py, hamlet/command/manage/stack.py, hamlet/command/run/lambda_func.py, hamlet/command/run/pipeline.py, hamlet/command/run/task.py
- Add deprecation notices for commands which have moved into contract based execution processes
The commands current map directly to bash scripts in the bash executor which are scheduled for removal in the next major release. This starts the process of getting them removed
- None
- None
- None
=> refactor: deprecate commands replaced by runbooks and native commands

hamlet/backend/common/http_client.py, hamlet/backend/container_registry/__init__.py
- Removes the custom transport option used for the container image client as it also disables the use of env proxy configuration
- Creates a standard http client that should be used hamlet overall to ensure consistency in the use of the http client
When running the hamlet cli in locked down environments where outbound DNS lookups are disabled using the transport client would disable any proxy settings and cause the connection to fail.
Tested locally
- None
- None
- None
=> fix: remove use of transport from httpx client

hamlet/backend/run/expo_app_publish/__init__.py, hamlet/command/run/expo_app_publish.py, tests/unit/command/run/test_expo_app_publish.py
- Removes the parameters used in the expo_app_publish cli command which have now been removed from the underlying bash scripts
Aligns with the changes made in https://github.com/hamlet-io/executor-bash/pull/348
Tested locally
- https://github.com/hamlet-io/executor-bash/pull/348
- None
- None
=> refactor: remove deprecated expo_app_publish param

hamlet/backend/run/sentry_release/__init__.py, hamlet/command/run/sentry_release.py, tests/unit/command/run/test_sentry_release.py
Adds -d option to support --dist argument for sentry releases command
Sentry now requires distribution to be set along with the release during source maps upload for correct error processing.
Locally
- None
- None
- None
=> feat: add dist option for sentry release

hamlet/backend/contract/tasks/aws_ecr_docker_login/__init__.py
- uses subprocess and the native docker client to login to ecr registries
- The docker-py client doesn't save logins across sessions and stores the logins outside of the standard client login process
- This ensures that the login is provided to the docker client on the machine so that other runbook steps work as expected
tested locally
- None
- None
- None
=> fix: ecr docker login process

.github/workflows/changelog.yml, .github/workflows/release.yml, .github/workflows/style.yml, hamlet/backend/generate/utils.py, hamlet/backend/test/templates/cfn_lint_test_func_block.py, hamlet/backend/test/templates/checkov_test_func_block.py, setup.py
- Remove the cfn-linkt, checkov and diagrams packages from base dependencies
- Make python3.7 the minimum supported version
- Remove the need to install importlib as its an included package in 3.7
- Remove changelog generation on pull requests
- Update gh action versions
This makes it easier to install hamlet as the package size should be considerably smaller. 
Checkov creates dependency issues as it adds the awscliv1 into python packages, with v2 no longer distribued as a pip package this causes downgrades from v2 -> v1 if python packages are first on a users path
Tested locally
- None
- None
- None
=> refactor: package management

hamlet/backend/contract/tasks/file_zip_path/__init__.py
-  Fixes the healthcheck for the zip task to validate checksums on the zip instead of looking for a specific file
Current task was failing as a filename was expected which can't be guaranteed inside the zip file at this stage
Tested locally
- None
- None
- None
=> fix: zip checking for zip task

hamlet/backend/generate/utils.py, setup.py
- Some native python3 installs (awslinux) are using 3.6 and lower of python. Using this backport ensures everything works on them
Keep compatibility with old python versions
tested locally
- None
- None
- None
=> fix: add importlib_resources for backwards compat

hamlet/backend/container_registry/__init__.py
- When using a Container Registry that supports OCI images the manifest returned can either be a single manifest or an index that contains a list of multi platform manifests
- Adds support for handling these manifests with initial preference for the linux based os as we don't use them to run images
With release https://github.com/docker/build-push-action/releases/tag/v3.3.0 of the docker build push action the version of BuildX was updated which now creates two manifest entries for every image. As a result new images were pushed up with an index manifest and the hamlet container registry client didn't understand that change. 
Tested locally and with test suite. 
- None
- None
- …
=> feat: add support for OCI image indexes

hamlet/backend/generate/utils.py
- Add an extra exception raised on python36 when the importlib resource module isn't available
This ensures that hamlet works on older versions of python which are used in base OS images
Tested locally
- None
- None
- None
=> fix: handle import failure for py36 compat

hamlet/backend/contract/tasks/set_provider_credentials/__init__.py
Fix the path for sh script which is executed set_provider_credentails task
The current hamlet cli version is failing.
locally
- None
- None
- None
=> fix: path to the sh script for set_provider_credentails task

setup.py
Fixes an issue in docker-py where the urllib3 package isn't pinned and doesn't support version 3 of the package 
https://github.com/docker/docker-py/issues/3113
Deployments failing if the older version was't picked up by depdencies
- None
- None
- None
=> fix: pin urllib to version 2
